name: Deploy
on: push

jobs:
  s3-deploy:
    name: S3 Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Install Dependencies
        run: npm ci
      - uses: concord-consortium/s3-deploy-action@v1
        with:
          bucket: models-resources
          prefix: compute-engine
          folderToDeploy: s3-dist
          build: ./scripts/github-build.sh
          awsAccessKeyId: ${{ secrets.AWS_ACCESS_KEY_ID }}
          awsSecretAccessKey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
